export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_USER: "SET_USER",
    SET_TRACK: "SET_TRACK",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYSTATE: "SET_PLAYSTATE",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
}